### ISSUE TITLE
小白还不会使用啊？请问有教程吗？

### ISSUE THREAD

**Issue by 889098** [bill080307/VideoShare#7]
并不是直接传到服务器就可以安装啊，请问可以出个教程吗？

**Comment by sunminghong** [comment]
请问，里面的home和videolist 页面请求的各种。json文件在哪？

**Comment by bill080307** [comment]
无需服务器，只要ipfs节点就可以使用，我这一份就已经部署到公网上了。

**Comment by bill080307** [comment]
当然欢迎修改我的源码，自行写入密钥，自行发布。

**Comment by bill080307** [comment]
> 请问，里面的home和videolist 页面请求的各种。json文件在哪？

这是一个很好的问题，我项目里面有一个叫dashboard的前端项目，这一个前端与ipfs节点进行交互、操作ipfs，就可以生成出需要的json文件。

**Comment by 889098** [comment]
@bill080307 能否出一个傻瓜教程啊，小白想搞一下，真的不会啊

**Comment by 889098** [comment]
@bill080307 怎样部署到公网？

**Comment by bill080307** [comment]
@889098 目前还在开发，有兴趣部署可以自己编译一下，将dist文件集上传ipfs试一下。

**Comment by 889098** [comment]
@bill080307 可否发一份编译好的静态网站文件啊，感谢！924268440@qq.com

**Comment by bill080307** [comment]
> @bill080307 可否发一份编译好的静态网站文件啊，感谢！[924268440@qq.com](mailto:924268440@qq.com)

不行，以上的hash就是静态文件了，并且我加入了我的key

**Comment by 889098** [comment]
@bill080307 vue编译还比较麻烦呢

**Comment by bill080307** [comment]
@889098 我没有编译好的，静态文件，现在全在ipfs上。

**Comment by bill080307** [comment]
@889098 这是否是你的qq，我+；

**Comment by 889098** [comment]
@bill080307 是QQ啊，辛苦你了
